### PR TITLE
Add .is() DOM Filter

### PR DESCRIPTION
**Pull request by Wikiki**
add .is( selector) to filter collection
selector can be a DOM element, a DOMtastic instance or a string.

Take into account extended selector :visible :hidden

### CODE REVIEW

**Comment by webpro** [comment]
The `is` method sounds like a method that tries to do too much. FYI, there is a `matches` function that works like this:

```
$.matches(element, '.b')
```

Or, you can check a class, e.g.:

```
$('.a').hasClass('b');
```

The latter can be modified to cater for the first. For a DOMtastic instance, there is:

```
const $element = $(document);
$element === $(element);
```

For a DOM element, you could do:

```
const element = document.body;
$(element).get(0) === element; // or:
$(element)[0] === element;
```

How about extending `matches` so we can do this:

```
$('.a').matches('.b')
```

We could then only pass a selector, though.

**Comment by Wikiki** [comment]
Hi,

thank for your answer but my point is more related to the chainability.
How to maintain the chainability with your proposales ?

Regards

**Comment by webpro** [comment]
Could you please elaborate on your use case? In which situation are you missing the chainability?

**Comment by webpro** [comment]
Closing this one due to inactivity.

**Pull request closed without merging**
