### PR TITLE
jQuery API for .filter(function)

### PR DESCRIPTION
**Pull request by dryabov**
jQuery API for .filter(function(index,element){}) (see http://api.jquery.com/filter/)

PS. Most likely similar patches should be applied for .each() and .map().

### CODE REVIEW

**Comment by webpro** [comment]
Thanks for your PR, but DOMtastic is not a drop-in for jQuery per se. This is a good example of something I don't like the jQuery API for.

**Comment by dryabov** [comment]
I don't like it as well (especially comparing callback arguments in $.map and $.fn.map), but it would simplify transition from jQuery to DOMtastic.

What about array_legacy module for those who like to have original jQuery API for each/filter/map?

**Comment by webpro** [comment]
Good idea, thanks. I think I like a separate "jquery-compat" option even better. I don't have time for this now, will look into it later (ideas welcome!).

**Comment by dryabov** [comment]
I've made a draft for jquery_compat module: https://github.com/dryabov/DOMtastic/commit/561a45, but there should be a way to exclude the module from default build (otherwise current tests are not passed).

**Comment by webpro** [comment]
@dryabov, I've created a `--jquery-compat` option for the custom build in the master branch (3b9428286af829bc3299c47afced00cb1c1f6ac1). You can use it like this:

    bin/custom --jquery-compat

Could you please try this from the master branch (I've not released this yet), and see if it works for you?

**Comment by webpro** [comment]
Also, I've fixed the issue you mentioned in https://twitter.com/dryabov/status/573493744865009664.

**Comment by dryabov** [comment]
Thanks.

**Pull request closed without merging**
