### PR TITLE
Add :visible :hidden selectors to filter

### PR DESCRIPTION
**Pull request by Wikiki**
Add the possibility to use a selector integrating :visible or :hidden condition like:

‘.myDiv:visible’

### CODE REVIEW

**Comment by webpro** [comment]
I'm sorry, but I'm going to reject this PR. This library is not meant as a drop-in replacement for jQuery. It only has a subset of jQuery's features, to keep it small and fast. Please note that you can extend `$.fn` to your needs.

**Comment by matt3224** [comment]
@coveralls did you ever write a function to do this?

**Comment by Wikiki** [comment]
@matt3224 if you want you can have a look on the files of my PR, I proposed a function to handle this.

**Comment by matt3224** [comment]
Im not sure how to add this in as a chainable method

**Pull request closed without merging**
